/**
 * Chrome background sRGB hex snapshot. Regenerated by
 * `packages/core/scripts/generate-chrome-tokens.ts` from the `--sidebar`
 * Tailwind token in `packages/app/src/globals.css`. Drift between this
 * file and the CSS is caught by `chrome.test.ts`.
 *
 * Consumers:
 *   - `packages/core/src/constants/chrome.test.ts` — drift sentinel: any
 *     CSS edit that changes the resolved hex without a corresponding
 *     regeneration of this file fails the test, surfacing the change in
 *     the PR diff.
 *   - `packages/app/src/build/chrome-tokens-vite-plugin.test.ts` —
 *     reference target: the build-time substitution must produce these
 *     exact values from the live CSS.
 *
 * The build pipeline itself does NOT import these constants — `chrome-
 * tokens-vite-plugin.ts` resolves the hex from the live CSS via
 * `chrome-resolver.ts`. The runtime renderer reads the substituted hex
 * from `packages/app/index.html`'s inline `<style>` placeholders. The
 * Electron main process never imports this file: under `transparent:
 * true` + vibrancy, `BrowserWindow.setBackgroundColor` is a no-op, so
 * `DEFAULT_WIN_OPTS` no longer carries a `backgroundColor` field.
 *
 * Do NOT hand-edit. Run `bun run packages/core/scripts/generate-chrome-tokens.ts`
 * after changing `--sidebar` in globals.css.
 */
export const CHROME_BG_LIGHT = '#fafafa' as const;
export const CHROME_BG_DARK = '#171717' as const;
