/**
 * Resolve the `--sidebar` Tailwind v4 token from `packages/app/src/globals.css`
 * to sRGB hex strings. Single source of truth for desktop chrome background:
 *
 *   - `packages/core/src/constants/chrome.ts` (regenerated by
 *     `scripts/generate-chrome-tokens.ts`)
 *   - `packages/app/index.html` inline `<style>` (placeholders substituted at
 *     build time by `packages/app/src/build/chrome-tokens-vite-plugin.ts`)
 *
 * Drift between the parsed CSS and the committed `chrome.ts` constants is
 * caught by `packages/core/src/constants/chrome.test.ts`.
 *
 * Node-only — uses `node:fs` and the `culori` colorspace converter.
 */
import { readFileSync } from 'node:fs';
import { formatHex, parse as parseColor } from 'culori';

export interface ChromeTokens {
  /** sRGB hex string for the light-mode chrome background (e.g. `#fafafa`). */
  light: string;
  /** sRGB hex string for the dark-mode chrome background (e.g. `#171717`). */
  dark: string;
}

/**
 * Match `--sidebar: <value>;` inside a CSS block. The block matchers below
 * scope the search to `:root { ... }` (light) and `.dark { ... }` (dark)
 * blocks that contain a `--sidebar` declaration — a `.dark .descendant`
 * selector or a `:root` block that doesn't carry `--sidebar` is skipped.
 */
const SIDEBAR_DECL_RE = /--sidebar:\s*([^;]+);/;

/**
 * Find every top-level block matching the given selector exactly (e.g.
 * `:root` matches `:root {` but not `:root .foo {`; `.dark` matches `.dark {`
 * but not `.dark .activity-panel-diff {`). Returns each block's inner body.
 *
 * Exported so the preview-theme-token resolver can reuse the same exact-match
 * block scanner (it parses the identical `:root` / `.dark` / `@theme` blocks).
 */
export function findBlockBodies(css: string, selector: string): string[] {
  // Standard MDN escape — every regex metacharacter (including `.`, `]`,
  // and `\`) is escaped exactly once with one backslash so `.dark` becomes
  // `\.dark` in the compiled pattern. The character class closes after
  // `\\` (one literal backslash) and the replacement `\\$&` produces a
  // single backslash in front of the matched metacharacter.
  const selectorRe = new RegExp(
    `(^|\\n)\\s*${selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\{`,
    'g',
  );
  const bodies: string[] = [];
  let match: RegExpExecArray | null = selectorRe.exec(css);
  while (match !== null) {
    const braceOpen = match.index + match[0].length - 1;
    let depth = 1;
    let cursor = braceOpen + 1;
    while (cursor < css.length && depth > 0) {
      const ch = css[cursor];
      if (ch === '{') depth += 1;
      else if (ch === '}') depth -= 1;
      if (depth === 0) {
        bodies.push(css.slice(braceOpen + 1, cursor));
        break;
      }
      cursor += 1;
    }
    if (depth !== 0) {
      throw new Error(`chrome-resolver: unbalanced braces while scanning ${selector}`);
    }
    match = selectorRe.exec(css);
  }
  return bodies;
}

function extractSidebarValue(css: string, selector: string): string {
  const bodies = findBlockBodies(css, selector);
  for (const body of bodies) {
    const decl = body.match(SIDEBAR_DECL_RE);
    if (decl && decl[1] !== undefined) {
      return decl[1].trim();
    }
  }
  throw new Error(`chrome-resolver: --sidebar declaration not found in any ${selector} block`);
}

function resolveToHex(cssColor: string, label: string): string {
  const parsed = parseColor(cssColor);
  if (parsed === undefined) {
    throw new Error(`chrome-resolver: culori failed to parse ${label} value: ${cssColor}`);
  }
  const hex = formatHex(parsed);
  if (hex === undefined) {
    throw new Error(`chrome-resolver: culori failed to convert ${label} to sRGB hex: ${cssColor}`);
  }
  return hex;
}

/**
 * Parse `--sidebar` from `:root` (light) and `.dark` blocks of the given CSS
 * file and resolve both to sRGB hex via culori.
 *
 * Throws on missing selector, missing declaration, unbalanced braces, or
 * unparseable color value. Callers handle once at build time — if any of
 * these fail, the build is the right thing to fail.
 */
export function resolveChromeTokensFromCss(cssPath: string): ChromeTokens {
  const css = readFileSync(cssPath, 'utf8');
  const lightValue = extractSidebarValue(css, ':root');
  const darkValue = extractSidebarValue(css, '.dark');
  return {
    light: resolveToHex(lightValue, 'light'),
    dark: resolveToHex(darkValue, 'dark'),
  };
}

/**
 * Render the resolved tokens as a TypeScript module body. Output stays byte-
 * stable so the regen script and the drift test can both anchor on it.
 */
export function renderChromeConstantsModule(tokens: ChromeTokens): string {
  return `/**
 * Chrome background sRGB hex constants. Regenerated by
 * \`packages/core/scripts/generate-chrome-tokens.ts\` from the
 * \`--sidebar\` Tailwind token in \`packages/app/src/globals.css\`. Drift
 * between this file and the CSS is caught by \`chrome.test.ts\`.
 *
 * Consumers:
 *   - \`packages/app/index.html\` inline <style> (Vite plugin substitutes
 *     placeholders at build time)
 *   - \`packages/desktop/src/main/index.ts\` BrowserWindow chrome
 *
 * Do NOT hand-edit. Run \`bun run packages/core/scripts/generate-chrome-tokens.ts\`
 * after changing \`--sidebar\` in globals.css.
 */
export const CHROME_BG_LIGHT = '${tokens.light}' as const;
export const CHROME_BG_DARK = '${tokens.dark}' as const;
`;
}
