/**
 * footnoteDefinition — PM block node for the `[^id]: text` definition syntax.
 *
 * Markdown source `[^id]: body text` (parsed by `remark-gfm`'s
 * mdast-util-gfm-footnote into `footnoteDefinition` mdast nodes) flows
 * through `index.ts`'s mdast→PM handler into this block. Round-trip via
 * remark-gfm's existing stringify path.
 *
 * Renders as an `<aside class="footnote-def">` styled as part of an
 * auto-numbered list at the foot of the document — Obsidian-parity
 * rendering. The visible numeric marker (`1.`, `2.`, …) is generated
 * via CSS `counter()` at the presentation layer, not in the renderHTML
 * tree. Each definition appends a back-reference arrow (`↩`) linking
 * to the reference's `<sup id="fnref-{id}">`. Bodies hold arbitrary
 * block-level content (paragraphs, lists, etc.) so authors can write
 * formatted footnote bodies, not just plain text.
 *
 * Linked to `footnoteReference` (`extensions/footnote-reference.ts`) by
 * the `identifier` attr. Anchor `id="fn-{identifier}"` on the rendered
 * aside makes the reference's `<a href="#fn-{identifier}">` link
 * functional in static-output destinations (clipboard HTML, docs site,
 * etc.).
 */

import { Node } from '@tiptap/core';

declare module '@tiptap/core' {
  interface Commands<ReturnType> {
    footnoteDefinition: {
      /** Insert a footnote definition with the given identifier + an empty paragraph body. */
      insertFootnoteDefinition: (identifier: string) => ReturnType;
    };
  }
}

export const FootnoteDefinition = Node.create({
  name: 'footnoteDefinition',
  group: 'block',
  content: 'block+',
  defining: true,
  priority: 60,

  addAttributes() {
    return {
      identifier: { default: '' },
      label: { default: null },
    };
  },

  parseHTML() {
    // Extract `identifier` from `data-footnote-id` (renderHTML emits it
    // there + on `id="fn-{id}"`). Without `getAttrs`, TipTap looks for a
    // DOM attribute literally named `identifier`, which doesn't exist —
    // clipboard paste would land with `identifier: ''` and silently break
    // reference→definition pairing. Mirrors wiki-link/math-inline.
    const getAttrs = (node: HTMLElement | string) => {
      if (typeof node === 'string') return false;
      const id = node.getAttribute('data-footnote-id') || '';
      return { identifier: id, label: id || null };
    };
    return [
      { tag: 'aside[data-footnote-def]', getAttrs },
      { tag: 'aside.footnote-def', getAttrs },
    ];
  },

  renderHTML({ node, HTMLAttributes }) {
    const id = String(node.attrs.identifier ?? '');
    return [
      'aside',
      {
        ...HTMLAttributes,
        'data-footnote-def': '',
        'data-footnote-id': id,
        id: `fn-${id}`,
        class: 'footnote-def',
      },
      // Children slot — `0` tells PM to render NodeViewContent here. The
      // visible numeric marker is generated by CSS counter() in
      // `globals.css` so definitions auto-number 1., 2., 3. in document
      // order regardless of identifier.
      ['div', { class: 'footnote-body' }, 0],
      // Back-reference arrow linking to the reference site
      // (`<sup id="fnref-{id}">`). `contentEditable: 'false'` keeps the
      // arrow as static chrome — authors edit the body, not the arrow.
      [
        'a',
        {
          href: `#fnref-${id}`,
          class: 'footnote-backref',
          contentEditable: 'false',
          'aria-label': 'Back to reference',
        },
        '↩',
      ],
    ];
  },

  addCommands() {
    return {
      insertFootnoteDefinition:
        (identifier) =>
        ({ commands }) =>
          commands.insertContent({
            type: this.name,
            attrs: { identifier, label: identifier },
            content: [{ type: 'paragraph' }],
          }),
    };
  },
});
